In [ ]:
from fsa_utils import convert_FSA_to_MPS

states = [0, 1]
inputs = [0, 1]
begin_state = [0]
final_state = [1]

transitions_W = {
        0: {0: 0, 1: 1}, # {i:{X:Y}} => At site i : if input is X : go to state Y
        1: {0: 1}
    }
transitions_L_2 = {
        0: {0: 1, 1: 0}, # {i:{X:Y}} => At site i : if input is X : go to state Y
        1: {1: 0}
    }

In [8]:
A, v_l, v_r = convert_FSA_to_MPS(states, inputs, transitions_W, begin_state, final_state)

In [9]:
print("A : ", A,'\n', "v_l: ", v_l,'\n', "v_r: ",v_r)

A :  [[[1 0]
  [0 1]]

 [[0 1]
  [0 0]]] 
 v_l:  [1 0] 
 v_r:  [[0]
 [1]]


In [23]:
import numpy as np

n = 5
quantum_state = np.eye(n, dtype=int)

In [24]:
quantum_state

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [25]:
quantum_state_MPs = np.zeros((quantum_state.shape[0], quantum_state.shape[1], A.shape[1], A.shape[2]))

In [26]:
for i in range(quantum_state.shape[0]):
    for j in range(quantum_state.shape[1]):
        quantum_state_MPs[i,j] = A[quantum_state[i][j]]

In [28]:
quantum_state_MPs.shape

(5, 5, 2, 2)

In [22]:
A

array([[[1, 0],
        [0, 1]],

       [[0, 1],
        [0, 0]]])