In [96]:
import numpy as np
from math import comb
import qiskit

In [ ]:
### LETS do the Dicke test here.

def prod_cs_red(n,k,i,m,r,c):
    res = 0
    if c==(r+m):
        res = np.sqrt(comb(n-i,k-r-m)*comb(1,m)/comb(n+1-i,k-r))
    return res


def build_A_dicke(n,k,i,m):
    #n is the system size
    #k is the number of 1s in the dicke state
    #i is the index of the system register (runs from 1 to n)
    #m is the qubit register in {0,1}
    n_anc = k+1
    Aim = np.zeros((n_anc, n_anc))
    for r in range(n_anc):
        for c in range(n_anc):
            Aim[r,c] = prod_cs_red(n,k,i,m,r,c)
    return Aim


def build_A_list_dicke(n,k):
    A_list = []
    for i in range(1,n+1):
        for m in [0,1]:
            A_list.append(build_A_dicke(n,k,i,m))
    return A_list


n=3 #the system size
k=1 # the number of ones
n_anc = k+1 # the ancillary dimension
#m values can be either 0 or 1
#m=0
i=1

A_list = build_A_list_dicke(n,k)
print(A_list)

[array([[0.81649658, 0.        ],
       [0.        , 1.        ]]), array([[0.        , 0.57735027],
       [0.        , 0.        ]]), array([[0.70710678, 0.        ],
       [0.        , 1.        ]]), array([[0.        , 0.70710678],
       [0.        , 0.        ]]), array([[0., 0.],
       [0., 1.]]), array([[0., 1.],
       [0., 0.]])]


In [93]:


# Define the matrices
A_0 = np.array([[1, 0], [0, 0]])
A_1 = np.array([[0, 0], [0, 1]])

# Define the r_state vector
r_state = np.array([1/np.sqrt(2), 1/np.sqrt(2)])

# Print the matrices and r_state vector
print("A_0 matrix:")
print(A_0)

print("\nA_1 matrix:")
print(A_1)

print("\nr_state vector:")
print(r_state)

A_0 matrix:
[[1 0]
 [0 0]]

A_1 matrix:
[[0 0]
 [0 1]]

r_state vector:
[0.70710678 0.70710678]


In [94]:
N_sys = 2
n_ancilla = 1
init_sys = [1,0,0,0]
init_anc = [1,1]/np.sqrt(2)

init_state = np.kron(init_sys, init_anc)
print(init_state)

#we need to permutedims when applying to the sites

big_A_matrix = np.zeros((4,4))
big_A_matrix[:2, :2] = A_0         # Top-left block
big_A_matrix[:2, 2:] = -A_1        # Top-right block
big_A_matrix[2:, :2] = A_1         # Bottom-left block
big_A_matrix[2:, 2:] = A_0  

#1st permutedims of 0 goes to 1 of the init state
id_2 = np.eye(2)
print(big_A_matrix)

op_U = np.kron(id_2, big_A_matrix)


init_state = np.reshape(init_state, (2,2,2))
init_state = np.transpose(init_state, (1,0,2))
init_state = np.reshape(init_state, (8))


res_state = op_U @ init_state.T


res_state = np.reshape(res_state, (2,2,2))
res_state = np.transpose(res_state, (1,0,2))
res_state = np.reshape(res_state, (8))


res_state = op_U @ res_state.T
print(res_state)







[0.70710678 0.70710678 0.         0.         0.         0.
 0.         0.        ]
[[ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]]
[0.70710678 0.         0.         0.         0.         0.
 0.         0.70710678]
